//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alertr.Shared.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alertr.Shared.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;a:&quot;1&quot;}.
        /// </summary>
        internal static string BadJson {
            get {
                return ResourceManager.GetString("BadJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;a&quot;:&quot;1&quot;}.
        /// </summary>
        internal static string GoodJson {
            get {
                return ResourceManager.GetString("GoodJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;id&quot;: 0,
        ///        &quot;guid&quot;: &quot;9686dead-d0fb-46fb-a081-04184eb40554&quot;,
        ///        &quot;isActive&quot;: true,
        ///        &quot;balance&quot;: &quot;$2,895.79&quot;,
        ///        &quot;picture&quot;: &quot;http://placehold.it/32x32&quot;,
        ///        &quot;age&quot;: 30,
        ///        &quot;eyeColor&quot;: &quot;blue&quot;,
        ///        &quot;name&quot;: &quot;Curry Bauer&quot;,
        ///        &quot;gender&quot;: &quot;male&quot;,
        ///        &quot;company&quot;: &quot;NAMEGEN&quot;,
        ///        &quot;email&quot;: &quot;currybauer@namegen.com&quot;,
        ///        &quot;phone&quot;: &quot;+1 (975) 588-3715&quot;,
        ///        &quot;address&quot;: &quot;730 Gain Court, Sunbury, Louisiana, 8612&quot;,
        ///        &quot;about&quot;: &quot;Reprehenderit  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HugeJson {
            get {
                return ResourceManager.GetString("HugeJson", resourceCulture);
            }
        }
    }
}
